#!/usr/bin/env php
<?php

require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/record-generator.php';

use DnsX\Adapter\TransIPAdapter;

$args = Docopt::handle(file_get_contents(__FILE__ . '.md'));

getEnvironment();

$infraDomain = getenv('INFRA_DOMAIN');
if (false === $infraDomain) {
    throw new \RuntimeException("No 'INFRA_DOMAIN' environment variable provided. Please check Config.");
}

$adapter = getTransIPAdapter();

$records = generateRecords();

try {
    echo "Setting DNS records on infra domain: $infraDomain\n";
    $adapter->setDnsRecords($infraDomain, $records);
} catch (\Exception $e) {
    echo $e->getMessage() . PHP_EOL;
    exit(-1);
}

function getTransIPAdapter()
{
    $username = getenv('TRANSIP_USERNAME');
    if (false === $username) {
        throw new \RuntimeException("No 'TRANSIP_USERNAME' environment variable provided. Please check Config.");
    }

    $key = getenv('TRANSIP_KEY');
    if (false === $key) {
        throw new \RuntimeException("No 'TRANSIP_KEY' environment variable provided. Please check Config.");
    }
    if (!file_exists($key)) {
        throw new \RuntimeException("'TRANSIP_KEY' is not pointing to a valid key file: " . $key);
    }
    $key = file_get_contents($key);

    return new TransIPAdapter($username, $key);
}
