#!/usr/bin/env php
<?php

require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/record-generator.php';

$args = Docopt::handle(file_get_contents(__FILE__ . '.md'));

getEnvironment();

$infraDomain = getenv('INFRA_DOMAIN');
if (false === $infraDomain) {
    throw new \RuntimeException("No 'INFRA_DOMAIN' environment variable provided. Please check Config.");
}

$records = generateRecords();

echo "Infra domain: $infraDomain" . PHP_EOL;
foreach ($records as $record) {
    echo $record->getName() . ' ' . $record->getType() . ' ' . $record->getTtl() . ' ' . $record->getValue() . PHP_EOL;
}
